### ISSUE TITLE
save_path, ec_cls are unused args to read_energy_files_parallel()

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/dscim#38]
https://github.com/ClimateImpactLab/dscim/blob/8a870c3e2e16fbc3077f33972c5ef59a9278bb7e/src/dscim/preprocessing/input_damages.py#L439

Not sure what's the intent here. "save_path" and "ec_cls" appear to be unused args. Might want to remove them or rewrite this and the docstr to avoid confusion as it's misleading.

**Comment by kemccusker** [comment]
Fixed by PR #56
